---
# Per environment values which override defaults in hmpps-person-record-manage-ui/values.yaml

generic-service:
  ingress:
    host: manage-person-record.hmpps.service.justice.gov.uk
    tlsSecretName: hmpps-person-record-cert-secret

  env:
    INGRESS_URL: "https://manage-person-record.hmpps.service.justice.gov.uk"
    HMPPS_AUTH_URL: "https://sign-in.hmpps.service.justice.gov.uk/auth"
    TOKEN_VERIFICATION_API_URL: "https://token-verification-api.prison.service.justice.gov.uk"
    PERSON_RECORD_API_URL: "https://hmpps-person-record.hmpps.service.justice.gov.uk"
    AUDIT_ENABLED: "false"

  allowlist:
    groups:
      - digital_staff_and_mojo
      - moj_cloud_platform

generic-prometheus-alerts:
  alertSeverity: hmpps-person-record-alerts-prod
